In [15]:
import os 
import sys

import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier, XGBRegressor
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt 
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [17]:
sys.path.append(r"c:\Users\keng-tse\Desktop\csi_tool") #這行為絕對路徑，如需使用，必須要修改為當前決路徑
import csi_tool

In [19]:
file_labels = {
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\0p.xlsx": 0,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\1p.xlsx": 1,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\2p.xlsx": 2,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\3p.xlsx": 3,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\4p.xlsx": 4,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1107_amp\5p.xlsx": 5,

}

In [21]:
def load_data(files_labels):
    data = []
    labels = []
    
    for file, label in files_labels.items():
        df = pd.read_excel(file)
        data.append(df.values)
        labels.extend([label] * len(df))  #Label all rows with the given label
    
    data = pd.DataFrame(np.vstack(data))  #Stack data vertically

    print(data)
    labels = pd.Series(labels)
    return data, labels

In [23]:
data, labels = load_data(file_labels)

              0           1           2           3           4           5   \
0      12.529964   24.000000   52.325902   80.808415   98.898938  141.428427   
1      38.600518   20.248457   23.021729   48.507731   66.037868  104.120123   
2      45.188494   33.541020   36.715120   45.891176   64.443774  109.370928   
3      44.598206   40.199502   34.132096   41.400483   65.007692  118.258192   
4     400.216192  394.574454  398.026381  394.656813  389.816624  381.379077   
...          ...         ...         ...         ...         ...         ...   
3131  325.013846  332.580817  336.879801  343.495269  342.125708  347.701021   
3132  330.945615  335.931541  330.315001  325.203014  333.839782  353.871446   
3133  329.607342  331.837310  333.216146  337.083076  337.544071  348.048847   
3134  321.596020  327.670566  335.871999  339.860265  338.710791  346.394284   
3135  323.047984  333.510120  337.379608  335.440010  340.828403  352.817233   

              6           7           8

In [25]:
#scaler = MinMaxScaler()
#data_scaled = scaler.fit_transform(data)

In [27]:
data_scaled =data

In [29]:
for i in range(1):
# PCA降維
    # n_components = 4  # 要保留的主成分數量
    # pca = PCA(n_components=n_components)
    # data_pca = pca.fit_transform(data_scaled)

    X_train, X_test, y_train, y_test = train_test_split(data_scaled, labels, test_size=0.2, random_state=39)
    smote = SMOTE()
    X_train, y_train = smote.fit_resample(X_train, y_train)
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train, y_train)

    #rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
    #rf_model.fit(X_train, y_train)

    #xgb_model = XGBClassifier(eval_metric='mlogloss')
    #xgb_model.fit(X_train, y_train)

    # 預測
    y_pred = knn.predict(X_test)
    #y_pred = xgb_model.predict(X_test)
    #y_pred = rf_model.predict(X_test)

    # 混淆矩陣和準確率
    print("==========", i)
    cm = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)

    print("Confusion Matrix:\n", cm)
    print(f"Accuracy: {accuracy * 100:.2f}%")
    report = classification_report(y_test, y_pred)
    print("Classification Report:\n", report)

========== 0
Confusion Matrix:
 [[127   2   0   0   0   0]
 [  1  73   1   0   0   0]
 [  0   0 115   0   0   0]
 [  0   0   0  83   0   0]
 [  0   0   0   0 160   1]
 [  0   1   0   0   1  63]]
Accuracy: 98.89%
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99       129
           1       0.96      0.97      0.97        75
           2       0.99      1.00      1.00       115
           3       1.00      1.00      1.00        83
           4       0.99      0.99      0.99       161
           5       0.98      0.97      0.98        65

    accuracy                           0.99       628
   macro avg       0.99      0.99      0.99       628
weighted avg       0.99      0.99      0.99       628



In [9]:
file_labels2 = {
    #label 與 資料對應
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\0p.xlsx": 0,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\1p.xlsx": 1,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\2p.xlsx": 2,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\3p.xlsx": 3,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\4p.xlsx": 4,
    r"C:\Users\keng-tse\Desktop\csi_tool\csi_dataset\peoplecounting\1023\5p.xlsx": 5,
}

In [10]:
data2, labels2 = load_data(file_labels2)

              0           1           2           3           4           5   \
0     294.703241  299.766576  304.507800  312.827428  310.961412  330.492057   
1     300.566132  303.211148  306.757233  302.483057  309.583591  330.629702   
2     299.821614  302.654919  301.303833  306.887602  307.605267  327.940543   
3     294.966100  302.364019  304.138127  307.883095  309.457590  328.811496   
4     435.983945  433.018475  438.346895  439.602093  454.757078  480.010417   
...          ...         ...         ...         ...         ...         ...   
4117  480.417527  480.884602  479.963540  478.658542  478.724347  478.452714   
4118  493.328491  485.000000  478.023012  473.600042  481.009355  482.346349   
4119  487.017453  489.540601  485.759200  479.009394  474.368001  477.177116   
4120  491.562814  486.065839  484.372790  480.550726  478.271889  474.843132   
4121  486.054524  488.878308  483.205960  478.150604  473.469112  483.662072   

              6           7           8

In [11]:
#data_scaled2 = scaler.fit_transform(data2)

data_scaled2 = data2
print(data_scaled2)

              0           1           2           3           4           5   \
0     294.703241  299.766576  304.507800  312.827428  310.961412  330.492057   
1     300.566132  303.211148  306.757233  302.483057  309.583591  330.629702   
2     299.821614  302.654919  301.303833  306.887602  307.605267  327.940543   
3     294.966100  302.364019  304.138127  307.883095  309.457590  328.811496   
4     435.983945  433.018475  438.346895  439.602093  454.757078  480.010417   
...          ...         ...         ...         ...         ...         ...   
4117  480.417527  480.884602  479.963540  478.658542  478.724347  478.452714   
4118  493.328491  485.000000  478.023012  473.600042  481.009355  482.346349   
4119  487.017453  489.540601  485.759200  479.009394  474.368001  477.177116   
4120  491.562814  486.065839  484.372790  480.550726  478.271889  474.843132   
4121  486.054524  488.878308  483.205960  478.150604  473.469112  483.662072   

              6           7           8

In [31]:
y_pred2 = knn.predict(data_scaled2)

In [33]:
print("==========", i)
cm = confusion_matrix(labels2, y_pred2)
accuracy = accuracy_score(labels2, y_pred2)

print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy * 100:.2f}%")
report = classification_report(labels2, y_pred2)
print("Classification Report:\n", report)

========== 0
Confusion Matrix:
 [[  0 704   4   0   1   0]
 [  4  20   7 510   0  21]
 [  0  53 430  61   2   9]
 [  4 623   2   0   4   4]
 [  1 322   1   0   1 579]
 [  0 523   1   0   0 231]]
Accuracy: 16.55%
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       709
           1       0.01      0.04      0.01       562
           2       0.97      0.77      0.86       555
           3       0.00      0.00      0.00       637
           4       0.12      0.00      0.00       904
           5       0.27      0.31      0.29       755

    accuracy                           0.17      4122
   macro avg       0.23      0.19      0.19      4122
weighted avg       0.21      0.17      0.17      4122



In [35]:
xgb_reg_model = XGBRegressor(eval_metric='rmse')
xgb_reg_model.fit(X_train, y_train)

# Prediction for regression
y_pred_reg = xgb_reg_model.predict(X_test)

# Mean squared error for regression
mse = mean_squared_error(y_test, y_pred_reg)
print("\n========== Regression Results ==========")
print(f"Mean Squared Error: {mse:.4f}")

mder = mean_absolute_error(y_test, y_pred_reg)
print("\n========== Regression Results ==========")
print(f"Mean absolute Error: {mde:.4f}")


========== Regression Results ==========
Mean Squared Error: 0.0997

========== Regression Results ==========


NameError: name 'mde' is not defined

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
import numpy as np

# Ensure y_test and y_pred_reg are numpy arrays if they're pandas Series
y_test = np.array(y_test)  # Convert y_test to numpy if it's a pandas Series
y_pred_reg = np.array(y_pred_reg)  # Convert y_pred_reg to numpy if it's a pandas Series

# Calculate MSE for each label
labels_unique = np.unique(y_test)  # Assuming 'y_test' contains categorical labels (discrete labels)
mse_per_label = []

for label in labels_unique:
    # Get the indices where the label occurs in the true labels
    indices = np.where(y_test == label)[0]  # Extract the first element of the tuple (indices)
    
    # Get the true and predicted values for this label
    y_true_label = y_test[indices]
    y_pred_label = y_pred_reg[indices]
    
    # Calculate MSE for this label
    mse = mean_squared_error(y_true_label, y_pred_label)
    mse_per_label.append(mse)

# Plotting the MSE per label
plt.figure(figsize=(10, 6))
plt.bar(labels_unique, mse_per_label, color='skyblue', edgecolor='black')
plt.title('MSE for Each Label in Regression')
plt.xlabel('Label')
plt.ylabel('Mean Squared Error')
plt.xticks(labels_unique, rotation=45)  # Rotate x-axis labels if needed for clarity
plt.show()

In [ ]:
# Prediction for regression
y_pred_reg2 = xgb_reg_model.predict(data_scaled2)

# Mean squared error for regression
mse2 = mean_squared_error(labels2,y_pred_reg2)
print("\n========== Regression Results ==========")
print(f"Mean Squared Error: {mse2:.4f}")

mde2 = mean_absolute_error(labels2,y_pred_reg2)
print("\n========== Regression Results ==========")
print(f"Mean absolute Error: {mde2:.4f}")

In [ ]:
# Ensure y_test and y_pred_reg are numpy arrays if they're pandas Series
labels2 = np.array(labels2)  # Convert y_test to numpy if it's a pandas Series
y_pred_reg2 = np.array(y_pred_reg2)  # Convert y_pred_reg to numpy if it's a pandas Series

# Calculate MSE for each label
labels_unique = np.unique(labels2)  # Assuming 'y_test' contains categorical labels (discrete labels)
mse_per_label = []

for label in labels_unique:
    # Get the indices where the label occurs in the true labels
    indices = np.where(labels2 == label)[0]  # Extract the first element of the tuple (indices)
    
    # Get the true and predicted values for this label
    y_true_label = labels2[indices]
    y_pred_label = y_pred_reg2[indices]
    
    # Calculate MSE for this label
    mse = mean_squared_error(y_true_label, y_pred_label)
    mse_per_label.append(mse)

# Plotting the MSE per label
plt.figure(figsize=(10, 6))
plt.bar(labels_unique, mse_per_label, color='skyblue', edgecolor='black')
plt.title('MSE for Each Label in Regression')
plt.xlabel('Label')
plt.ylabel('Mean Squared Error')
plt.xticks(labels_unique, rotation=45)  # Rotate x-axis labels if needed for clarity
plt.show()